apiVersion: v1
kind: Pod
metadata:
  name: train-test
  namespace: bbhnet
spec:
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: nvidia.com/gpu.product
  #           operator: In
  #           values:
  #           - "Tesla-V100-SXM2-32GB"
  restartPolicy: Never
  containers:
  - name: mypod
    image: ghcr.io/alecgunny/bbhnet/train:latest
    resources:
      limits:
        memory: 32G
        cpu: 16
        nvidia.com/gpu: 1
      requests:
        memory: 32G
        cpu: 16
        nvidia.com/gpu: 1
    env:
    - name: AWS_ENDPOINT_URL
      value: "http://rook-ceph-rgw-nautiluss3.rook"
    envFrom:
    - secretRef:
        name: wandb-api-key
    - secretRef:
        name: aws-credentials
    command: ["python"]
    args:
    - "/opt/aframe/aframe/train/train/main.py"
    - "--config=/opt/aframe/aframe/pipelines/configs/train.yaml"
    - "--data.ifos=[H1,L1]"
    - "--data.data_dir=s3://aframe-test"
    - "--trainer.logger=WandbLogger"
    - "--trainer.logger.save_dir=s3://aframe-results/k8s-test"
    - "--trainer.logger.entity=ml4gw"
    - "--trainer.logger.project=aframe"
