# commented args represent values filled out
# by train task at run time. To build a functional
# standalone config, add these in

model:
  # architecture
  arch:
    class_path: aframe.architectures.ResNet
    init_args:
      layers: [3, 4, 6, 3]
      norm_groups: 16
  metric:
    class_path: train.validation.TimeSlideAUROC
    init_args:
      max_fpr: 1e-3
      pool_length: 8

  # optimization params
  learning_rate: 0.000585
  pct_lr_ramp: 0.115
data:
  # loading args
  # data_dir:
  # ifos:

  # preprocessing args
  batch_size: 384
  kernel_length: 1.5
  psd_length: 8
  fduration: 1
  highpass: 32
  fftlength: null

  # augmentation args
  waveform_prob: 0.277
  snr_thresh: 4
  max_snr: 100
  snr_alpha: 3
  swap_frac: 0.014
  mute_frac: 0.055
  trigger_pad: -0.75

  # validation args
  valid_frac: 0.25
  valid_stride: 0.5
  num_valid_views: 4
  valid_livetime: 86400
trainer:
  # by default, use a local CSV logger.
  # Options in train task for using a
  # wandb logger instead
  logger:
    - class_path: lightning.pytorch.loggers.CSVLogger
      init_args:
        # save_dir:
        flush_logs_every_n_steps: 10
  # devices:
  # strategy: set to ddp if len(devices) > 1
  precision: 16-mixed
  accelerator: auto
  max_epochs: 200
  check_val_every_n_epoch: 1
  log_every_n_steps: 20
  benchmark: true
