name: container-build 
on: push
env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - 
      name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
  
    - 
      name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # build the singularity image inside a docker container
    # that has singularity installed (take a big breath).
    # Then dump the singularity image into a squashed filesystem
    # that we can use in our base container.
    # TODO: could we just do this directly to a
    # sandbox and not have to deal with squashing
    # and unsquashing?
    -
      name: Build singularity image
      run: |
        docker run \
          --rm \
          -v ${{ github.workspace }}:/opt/aframe \
          --workdir /opt/aframe/aframe/train \
          --privileged \
          --entrypoint /bin/bash \
          quay.io/singularity/singularity:v3.8.1 \
          -c 'singularity build --sandbox /tmp/app train.def && tar -czf /opt/aframe/app.tar.gz /tmp/app --remove-files'

    # now copy the fs contents into an empty
    # container and push it to the registry
    - 
      name: build docker image
      env:
        tag: ${{ env.REGISTRY }}/alecgunny/bbhnet/train:latest
      run: |
        cat app.tar.gz | docker import - ${{ env.tag }}
        docker push ${{env.tag }}
  