name: container-build 
on: push
env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: quay.io/singularity/singularity:v3.8.1
        options: --privileged

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - 
      name: Build Container
      # run: |
      #   cd aframe/train
      #   singularity build train.sif train.def
      run: singularity build dummy.sif dummy.def

    -
      name: Dump container contents
      run: |
        singularity sif dump 4 dummy.sif > dummy.squash
    - name: upload artifact
      uses: actions/upload-artifact@master
      with:
        name: dummy
        path: dummy.squash
  push:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - 
      name: Checkout repository
      uses: actions/checkout@v4
  
    - 
      name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - 
      name: download squash
      uses: actions/download-artifact@master
      with:
        name: dummy
    - 
      name: delete artifact
      uses: geekyeggo/delete-artifact@v2
      with:
        name: dummy

    - 
      name: build docker image
      env:
        tag: ${{ env.REGISTRY }}/alecgunny/bbhnet/dummy:latest
      run: |
        unsquashfs -d apptainer dummy.squash
        docker build -t ${{ env.tag }} .
        docker push ${{env.tag }}
  
