name: container-build 
on: push
env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - 
      name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
  
    - 
      name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build singularity image
      run: |
        docker run -v ${{ github.workspace }}:/opt/aframe \
          --workdir /opt/aframe/aframe/train \
          quay.io/singularity/singularity:v3.8.1 \
          /bin/bash -c 'singularity build app.sif train.def && singularity sif dump 4 app.sif > app.squash'
    - 
      name: build docker image
      env:
        tag: ${{ env.REGISTRY }}/alecgunny/bbhnet/train:latest
      run: |
        unsquashfs -d apptainer app.squash
        docker build -t ${{ env.tag }} .
        docker push ${{env.tag }}
  